### ISSUE TITLE
It doesn't seem to work for me.

### ISSUE THREAD

**Issue by ZekePolarisBSH** [gargolito/search-pypi#1]
It could be the thing I need no longer exists?
pyautogui

**Comment by gargolito** [comment]
Sorry, I totally missed this.

**Comment by ZekePolarisBSH** [comment]
Sorry what did you missed?

**Comment by gargolito** [comment]
your one year old issue on my app.

**Comment by ZekePolarisBSH** [comment]
Ohhh yeaaa, I wonder if it works now.

**Comment by gargolito** [comment]
pyautogui is not a dependency, do you mean that the script didn't find it? I just tried it and it worked just fine.

**Comment by ZekePolarisBSH** [comment]
If I can remember the full reason what issue I was having then I can
remember what it was doing... Everything I did a year ago has been deleted
by Google... Google fucked up everything...
